let arrayOne =["Einstien", 123, "Newton",1996, 1934,34,"lola","Edward","poland"];
document.write(arrayOne+"<br>");
let lengthofArray = arrayOne.length;
document.write("the length of array is "+ lengthofArray+"<br>");

arrayOne.push("Sania Mirza");
document.write("Sania Mirza added to end of array"+"<br>");
document.write("New Array is "+"<br>"+arrayOne+"<br>");
arrayOne.pop();
document.write("New Array is "+"<br>"+arrayOne+"<br>");
arrayOne.shift();
document.write("Einstein removed from array "+"<br>");
document.write("New Array is "+"<br>"+arrayOne);
arrayOne.unshift("Marie Curie");
document.write("Maire Curie added to array"+"<br>");
document.write("New Array is "+"<br>"+arrayOne+"<br>");
let slicedArray=arrayOne.slice(6,9);
document.write("New Array is created from existing array starting from index 6 to 8 "+"<br>");
document.write("New Array is "+"<br>"+slicedArray+"<br>");
let splicedArray = arrayOne.splice(4,9);
document.write("New Array is created from existing array starting from index 1 to 4 "+"<br>");
document.write("New Array is "+"<br>"+splicedArray+"<br>");
document.write(arrayOne);
arrayOne.splice(1,2);
document.write("<br>"+"new array: "+"<br>"+arrayOne+"<br>");
arrayThree = arrayOne.concat(slicedArray,splicedArray);
document.write("concatenated array"+"<br>"+arrayThree+"<br>");
arrayFour=[1,2,3,4];
arrayFour.splice(1,1,"mayy");
document.write(arrayFour+"<br>");
arrayFour[2]="element at index 2 modified";
document.write(arrayFour+"<br>");